# WARNING. THIS FILE IS AUTO-GENERATED. DO NOT MODIFY!
#
# This file contains build system settings derived from your snippets.
# Its contents are an implementation detail that should not be used outside
# of Zephyr's snippets CMake module.
#
# See the Snippets guide in the Zephyr documentation for more information.

###############################################################################
# Global information about all snippets.

# The name of every snippet that was discovered.
set(SNIPPET_NAMES "bt-ll-sw-split" "cdc-acm-console" "ci-shell" "diagnostic-logs" "hpf-gpio-icbmsg" "hpf-gpio-icmsg" "hpf-gpio-mbox" "hpf-mspi" "hw-flow-control" "matter-debug" "nordic-bt-rpc" "nordic-flpr" "nordic-flpr-xip" "nordic-log-stm" "nordic-log-stm-dict" "nordic-ppr" "nordic-ppr-xip" "nrf70-driver-debug" "nrf70-driver-verbose-debug" "nrf70-fw-patch-ext-flash" "nrf70-wifi" "nrf91-modem-trace-ext-flash" "nrf91-modem-trace-ram" "nrf91-modem-trace-rtt" "nrf91-modem-trace-uart" "nus-console" "power-consumption-tests" "ram-console" "rtt-console" "rtt-tracing" "serial-console" "tfm-enable-share-uart" "usbip-native-sim" "video-sw-generator" "wifi-credentials" "wifi-enterprise" "wifi-ip" "wifi-ipv4" "wifi-ipv6" "wpa-supplicant-debug" "xen_dom0" "zperf")
# The paths to all the snippet.yml files. One snippet
# can have multiple snippet.yml files.
set(SNIPPET_PATHS "E:/Code_Projects/nrf/snippets/ci-shell/snippet.yml" "E:/Code_Projects/nrf/snippets/hpf/gpio/icbmsg/snippet.yml" "E:/Code_Projects/nrf/snippets/hpf/gpio/icmsg/snippet.yml" "E:/Code_Projects/nrf/snippets/hpf/gpio/mbox/snippet.yml" "E:/Code_Projects/nrf/snippets/hpf/mspi/snippet.yml" "E:/Code_Projects/nrf/snippets/hw-flow-control/snippet.yml" "E:/Code_Projects/nrf/snippets/matter-debug/snippet.yml" "E:/Code_Projects/nrf/snippets/matter-diagnostic-logs/snippet.yml" "E:/Code_Projects/nrf/snippets/matter-power-consumption-tests/snippet.yml" "E:/Code_Projects/nrf/snippets/nordic-bt-rpc/snippet.yml" "E:/Code_Projects/nrf/snippets/nordic-flpr/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf70-driver-debug/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf70-driver-verbose-debug/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf70-fw-patch-ext-flash/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf70-wifi/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf91-modem-trace-ext-flash/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf91-modem-trace-ram/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf91-modem-trace-rtt/snippet.yml" "E:/Code_Projects/nrf/snippets/nrf91-modem-trace-uart/snippet.yml" "E:/Code_Projects/nrf/snippets/tfm-enable-share-uart/snippet.yml" "E:/Code_Projects/nrf/snippets/wpa-supplicant-debug/snippet.yml" "E:/Code_Projects/nrf/snippets/zperf/snippet.yml" "E:/Code_Projects/zephyr/snippets/bt-ll-sw-split/snippet.yml" "E:/Code_Projects/zephyr/snippets/cdc-acm-console/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-flpr-xip/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-flpr/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-log-stm-dict/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-log-stm/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-ppr-xip/snippet.yml" "E:/Code_Projects/zephyr/snippets/nordic-ppr/snippet.yml" "E:/Code_Projects/zephyr/snippets/nus-console/snippet.yml" "E:/Code_Projects/zephyr/snippets/ram-console/snippet.yml" "E:/Code_Projects/zephyr/snippets/rtt-console/snippet.yml" "E:/Code_Projects/zephyr/snippets/rtt-tracing/snippet.yml" "E:/Code_Projects/zephyr/snippets/serial-console/snippet.yml" "E:/Code_Projects/zephyr/snippets/usbip-native-sim/snippet.yml" "E:/Code_Projects/zephyr/snippets/video-sw-generator/snippet.yml" "E:/Code_Projects/zephyr/snippets/wifi-credentials/snippet.yml" "E:/Code_Projects/zephyr/snippets/wifi-enterprise/snippet.yml" "E:/Code_Projects/zephyr/snippets/wifi-ip/snippet.yml" "E:/Code_Projects/zephyr/snippets/wifi-ipv4/snippet.yml" "E:/Code_Projects/zephyr/snippets/wifi-ipv6/snippet.yml" "E:/Code_Projects/zephyr/snippets/xen_dom0/snippet.yml")

# Create variable scope for snippets build variables
zephyr_create_scope(snippets)

